#### zeros()
##### - 괄호안에 입력된 숫자만큼의 원소를 생성하고 9으로 초기화

In [1]:
import numpy as np
x = np.array([1,2,3])
y = np.zeros(shape=(10,), dtype=np.int8)
y
#type(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [2]:
x.shape

(3,)

#### mean()
##### - 평균값 계산

In [3]:
import numpy as np
list_1 = [1,2,3]
x = np.array(list_1)
x

array([1, 2, 3])

In [4]:
x.mean()

2.0

In [5]:
np.mean(x)

2.0

#### array()
##### 리스트나 튜플은 가능하지만 세트와 딕셔너리는 변환이 되지 않음

In [6]:
x = np.array([1,2,3])
y = np.array((1,2,3))
z = np.array({1,2,3})
w = np.array({"a":"b","a":"d"})
print(x, y, z, w)

[1 2 3] [1 2 3] {1, 2, 3} {'a': 'd'}


#### reshape()
##### 배열을 원하는 모양으로 생성 (갯수가 맞아야 생성가능)

##### 2차원

In [7]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b)
print('\n')
print(c)

[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##### 3차원 (인자를 -1로 주면 나머지 인자와 변환 되기 전의 배열을 토대로 알맞은 숫자를 자동으로 설정해줌)

In [8]:
a = np.arange(12)
b = np.reshape(a,(3,2,2))
c = np.reshape(a,(2,-1,2))
print(b, b.shape)
print('\n')
print(c, c.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] (3, 2, 2)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] (2, 3, 2)


#### ones() = zeros()랑 비슷하게 1로 채움

#### 배열 슬라이싱
##### 파이썬의 2차원 리스트에서 모든 원소의 원하는 번 째 원소들만 출력

In [9]:
import numpy as np
a = [[1,11],[2,12],[3,13],[4,14]]
print(a)
print('\n')
arr_a = np.array(a)
print(arr_a[:, 1])
print('\n')
print(arr_a[1:,1])

[[1, 11], [2, 12], [3, 13], [4, 14]]


[11 12 13 14]


[12 13 14]


#### math모듈의 sqrt()와 numpy모듈의 sqrt() 비교 (math는 숫자 하나만 가능하지만 numpy는 리스트 형식으로 많은 숫자를 한꺼번에 줄수 있다)

In [10]:
import math
math.sqrt(2)

1.4142135623730951

In [11]:
import numpy
numpy.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [12]:
x = np.zeros(15)
print(x)
y = x.reshape([5,3])
print(y)
z = np.zeros([3,5])
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 배열에 숫자를 더하면 전체 원소에 더해짐

In [13]:
x = np.zeros(15)
print(x)
y = x.reshape([5,3])
y += 4
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


### 전치 행렬
##### transpose()

In [14]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr,'\n')
trans_arr = arr.transpose()
print(trans_arr)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


### 2개 배열에 대한 연산
#### 각 배열의 인덱스 별로 계산

In [15]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x * y)
print(x**y) 

[ 4 10 18]
[  1  32 729]


### 인덱싱

In [16]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1]) 
print(x[1][1])
print(x[:,1]) #각 배열의 index = 1 을 출력

[4 5 6]
5
[2 5 8]


In [17]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[0] + y[2])
print(x * y[2])
print(x[:,1] * y[2])

[ 9 11 13]
[[ 8 18 30]
 [32 45 60]
 [56 72 90]]
[16 45 80]


#### random()

In [18]:
import numpy as np
ran1 = np.random.random(5)
print (ran1, ran1.shape)

[0.71748211 0.53250322 0.41949612 0.32161219 0.14363792] (5,)


In [19]:
# 0 ~ 1범위에서 난수 생성
ran2 = np.random.rand(2,3)
print (ran2, ran2.shape)

[[0.50968241 0.55220647 0.64781743]
 [0.15890213 0.40187107 0.7019371 ]] (2, 3)


In [20]:
ran3 = np.random.randint(3, size = 6)
print(ran3)
ran4 = np.random.randint(10, size = (2,5))
print(ran4)

[2 2 2 2 2 0]
[[8 2 2 2 4]
 [8 8 1 4 3]]


#### random.seed()

In [24]:
np.random.seed(123)
print(np.random.rand(2,3))

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]]


#### any(), all()

In [25]:
a = np.random.rand(5)
print(a > 0.2)
print(np.all(a > 0.2))
print(np.any(a > 0.2))

[ True  True  True  True  True]
True
True


#### linspace()

In [39]:
np.linspace(0,12, 4, retstep = True) # (시작값, 끝값, 나타낼 배열 원소 갯수) retstep = 간격 표시, endpoint = 마지막값 제외여부

(array([ 0.,  4.,  8., 12.]), 4.0)